src/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Motorbike__c.object
<CustomObject>
    <label>Motorbike</label>
    <nameField>
        <displayFormat>MOT-{0000}</displayFormat>
        <label>Motorbike Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Motorbikes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Car__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Car</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Motorbike__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Motorbike</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRAN-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MyTransaction.cls
public with sharing class MyTransaction
{
	private Transaction__c dto;

	public MyTransaction() {
		dto = new Transaction__c();
	}

	public MyTransaction(Id transactionId) {
		dto = [SELECT Id,Car__c,Motorbike__c,Amount__c from Transaction__c where Id = :transactionId];
	}

	public void setCarTransaction()
	{
		dto.Car__c = true;
	}

	public void setMotorbikeTransaction()
	{
		dto.Motorbike__c = true;
	}

	public void setAmount(Decimal amount)
	{
		dto.Amount__c = amount;
	}

	public void insertTransaction()
	{
		insert dto;
	}
}